services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: decree-ltd:local
    container_name: decree_web
    env_file:
      - ../.env
      - ../.env.web
    ports:
      - "4040:3000"
    networks:
      - marobix_default
    volumes:
      - decree_uploads:/app/data/uploads
    restart: unless-stopped

networks:
  marobix_default:
    external: true
    name: marobix_default

volumes:
  decree_uploads:
